<?php

namespace Database\Seeders;

use App\Models\DianMunicipality;
use Illuminate\Database\Seeder;

class DianMunicipalitiesSeeder extends Seeder
{
    public function run(): void
    {
        $municipalities = $this->getData();

        foreach (array_chunk($municipalities, 200) as $chunk) {
            DianMunicipality::upsert($chunk, ['code'], ['name', 'department_code', 'department_name']);
        }
    }

    /** @return array<int, array{code: string, name: string, department_code: string, department_name: string}> */
    private function getData(): array
    {
        return [
            ['code' => '05001', 'name' => 'Medellín', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05002', 'name' => 'Abejorral', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05004', 'name' => 'Abriaquí', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05021', 'name' => 'Alejandría', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05030', 'name' => 'Amagá', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05031', 'name' => 'Amalfi', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05034', 'name' => 'Andes', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05036', 'name' => 'Angelópolis', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05038', 'name' => 'Angostura', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05040', 'name' => 'Anorí', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05042', 'name' => 'Santafé de Antioquia', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05044', 'name' => 'Anzá', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05045', 'name' => 'Apartadó', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05051', 'name' => 'Arboletes', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05055', 'name' => 'Argelia', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05059', 'name' => 'Armenia', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05079', 'name' => 'Barbosa', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05086', 'name' => 'Belmira', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05088', 'name' => 'Bello', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05091', 'name' => 'Betania', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05093', 'name' => 'Betulia', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05101', 'name' => 'Ciudad Bolívar', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05107', 'name' => 'Briceño', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05113', 'name' => 'Buriticá', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05120', 'name' => 'Cáceres', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05125', 'name' => 'Caicedo', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05129', 'name' => 'Caldas', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05134', 'name' => 'Campamento', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05138', 'name' => 'Cañasgordas', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05142', 'name' => 'Caracolí', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05145', 'name' => 'Caramanta', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05147', 'name' => 'Carepa', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05148', 'name' => 'El Carmen de Viboral', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05150', 'name' => 'Carolina', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05154', 'name' => 'Caucasia', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05172', 'name' => 'Chigorodó', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05190', 'name' => 'Cisneros', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05197', 'name' => 'Cocorná', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05206', 'name' => 'Concepción', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05209', 'name' => 'Concordia', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05212', 'name' => 'Copacabana', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05234', 'name' => 'Dabeiba', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05237', 'name' => 'Don Matías', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05240', 'name' => 'Ebéjico', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05250', 'name' => 'El Bagre', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05264', 'name' => 'Entrerríos', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05266', 'name' => 'Envigado', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05282', 'name' => 'Fredonia', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05284', 'name' => 'Frontino', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05306', 'name' => 'Giraldo', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05308', 'name' => 'Girardota', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05310', 'name' => 'Gómez Plata', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05313', 'name' => 'Granada', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05315', 'name' => 'Guadalupe', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05318', 'name' => 'Guarne', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05321', 'name' => 'Guatapé', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05347', 'name' => 'Heliconia', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05353', 'name' => 'Hispania', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05360', 'name' => 'Itagüí', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05361', 'name' => 'Ituango', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05364', 'name' => 'Jardín', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05368', 'name' => 'Jericó', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05376', 'name' => 'La Ceja', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05380', 'name' => 'La Estrella', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05390', 'name' => 'La Pintada', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05400', 'name' => 'La Unión', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05411', 'name' => 'Liborina', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05425', 'name' => 'Maceo', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05440', 'name' => 'Marinilla', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05467', 'name' => 'Montebello', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05475', 'name' => 'Murindó', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05480', 'name' => 'Mutatá', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05483', 'name' => 'Nariño', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05490', 'name' => 'Necoclí', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05495', 'name' => 'Nechí', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05501', 'name' => 'Olaya', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05541', 'name' => 'Peñol', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05543', 'name' => 'Peque', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05576', 'name' => 'Pueblorrico', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05579', 'name' => 'Puerto Berrío', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05585', 'name' => 'Puerto Nare', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05591', 'name' => 'Puerto Triunfo', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05604', 'name' => 'Remedios', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05607', 'name' => 'Retiro', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05615', 'name' => 'Rionegro', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05628', 'name' => 'Sabanalarga', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05631', 'name' => 'Sabaneta', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05642', 'name' => 'Salgar', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05647', 'name' => 'San Andrés de Cuerquía', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05649', 'name' => 'San Carlos', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05652', 'name' => 'San Francisco', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05656', 'name' => 'San Jerónimo', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05658', 'name' => 'San José de la Montaña', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05659', 'name' => 'San Juan de Urabá', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05660', 'name' => 'San Luis', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05664', 'name' => 'San Pedro de los Milagros', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05665', 'name' => 'San Pedro de Urabá', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05667', 'name' => 'San Rafael', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05670', 'name' => 'San Roque', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05674', 'name' => 'San Vicente Ferrer', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05679', 'name' => 'Santa Bárbara', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05686', 'name' => 'Santa Rosa de Osos', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05690', 'name' => 'Santo Domingo', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05697', 'name' => 'El Santuario', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05736', 'name' => 'Segovia', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05756', 'name' => 'Sonsón', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05761', 'name' => 'Sopetrán', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05789', 'name' => 'Támesis', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05790', 'name' => 'Tarazá', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05792', 'name' => 'Tarso', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05809', 'name' => 'Titiribí', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05819', 'name' => 'Toledo', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05837', 'name' => 'Turbo', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05842', 'name' => 'Uramita', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05847', 'name' => 'Urrao', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05854', 'name' => 'Valdivia', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05856', 'name' => 'Valparaíso', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05858', 'name' => 'Vegachí', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05861', 'name' => 'Venecia', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05873', 'name' => 'Vigía del Fuerte', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05885', 'name' => 'Yalí', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05887', 'name' => 'Yarumal', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05890', 'name' => 'Yolombó', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05893', 'name' => 'Yondó', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '05895', 'name' => 'Zaragoza', 'department_code' => '05', 'department_name' => 'Antioquia'],
            ['code' => '08001', 'name' => 'Barranquilla', 'department_code' => '08', 'department_name' => 'Atlántico'],
            ['code' => '08078', 'name' => 'Baranoa', 'department_code' => '08', 'department_name' => 'Atlántico'],
            ['code' => '08137', 'name' => 'Campo de la Cruz', 'department_code' => '08', 'department_name' => 'Atlántico'],
            ['code' => '08141', 'name' => 'Candelaria', 'department_code' => '08', 'department_name' => 'Atlántico'],
            ['code' => '08296', 'name' => 'Galapa', 'department_code' => '08', 'department_name' => 'Atlántico'],
            ['code' => '08372', 'name' => 'Juan de Acosta', 'department_code' => '08', 'department_name' => 'Atlántico'],
            ['code' => '08421', 'name' => 'Luruaco', 'department_code' => '08', 'department_name' => 'Atlántico'],
            ['code' => '08433', 'name' => 'Malambo', 'department_code' => '08', 'department_name' => 'Atlántico'],
            ['code' => '08436', 'name' => 'Manatí', 'department_code' => '08', 'department_name' => 'Atlántico'],
            ['code' => '08520', 'name' => 'Palmar de Varela', 'department_code' => '08', 'department_name' => 'Atlántico'],
            ['code' => '08549', 'name' => 'Piojó', 'department_code' => '08', 'department_name' => 'Atlántico'],
            ['code' => '08558', 'name' => 'Polonuevo', 'department_code' => '08', 'department_name' => 'Atlántico'],
            ['code' => '08560', 'name' => 'Ponedera', 'department_code' => '08', 'department_name' => 'Atlántico'],
            ['code' => '08573', 'name' => 'Puerto Colombia', 'department_code' => '08', 'department_name' => 'Atlántico'],
            ['code' => '08606', 'name' => 'Repelón', 'department_code' => '08', 'department_name' => 'Atlántico'],
            ['code' => '08634', 'name' => 'Sabanagrande', 'department_code' => '08', 'department_name' => 'Atlántico'],
            ['code' => '08638', 'name' => 'Sabanalarga', 'department_code' => '08', 'department_name' => 'Atlántico'],
            ['code' => '08675', 'name' => 'Santa Lucía', 'department_code' => '08', 'department_name' => 'Atlántico'],
            ['code' => '08685', 'name' => 'Santo Tomás', 'department_code' => '08', 'department_name' => 'Atlántico'],
            ['code' => '08758', 'name' => 'Soledad', 'department_code' => '08', 'department_name' => 'Atlántico'],
            ['code' => '08770', 'name' => 'Suán', 'department_code' => '08', 'department_name' => 'Atlántico'],
            ['code' => '08832', 'name' => 'Tubará', 'department_code' => '08', 'department_name' => 'Atlántico'],
            ['code' => '08849', 'name' => 'Usiacurí', 'department_code' => '08', 'department_name' => 'Atlántico'],
            ['code' => '11001', 'name' => 'Bogotá D.C.', 'department_code' => '11', 'department_name' => 'Bogotá D.C.'],
            ['code' => '13001', 'name' => 'Cartagena de Indias', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13006', 'name' => 'Achí', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13030', 'name' => 'Altos del Rosario', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13042', 'name' => 'Arenal', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13052', 'name' => 'Arjona', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13062', 'name' => 'Arroyohondo', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13074', 'name' => 'Barranco de Loba', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13140', 'name' => 'Calamar', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13160', 'name' => 'Cantagallo', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13188', 'name' => 'Cicuco', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13212', 'name' => 'Córdoba', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13222', 'name' => 'Clemencia', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13244', 'name' => 'El Carmen de Bolívar', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13248', 'name' => 'El Guamo', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13268', 'name' => 'El Peñón', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13300', 'name' => 'Hatillo de Loba', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13430', 'name' => 'Magangué', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13433', 'name' => 'Mahates', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13440', 'name' => 'Margarita', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13442', 'name' => 'María La Baja', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13458', 'name' => 'Montecristo', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13468', 'name' => 'Santa Cruz de Mompox', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13473', 'name' => 'Morales', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13490', 'name' => 'Norosí', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13549', 'name' => 'Pinillos', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13580', 'name' => 'Regidor', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13600', 'name' => 'Río Viejo', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13620', 'name' => 'San Cristóbal', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13647', 'name' => 'San Estanislao', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13650', 'name' => 'San Fernando', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13654', 'name' => 'San Jacinto', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13655', 'name' => 'San Jacinto del Cauca', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13657', 'name' => 'San Juan Nepomuceno', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13667', 'name' => 'San Martín de Loba', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13670', 'name' => 'San Pablo', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13673', 'name' => 'Santa Catalina', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13683', 'name' => 'Santa Rosa', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13688', 'name' => 'Santa Rosa del Sur', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13744', 'name' => 'Simití', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13760', 'name' => 'Soplaviento', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13780', 'name' => 'Talaigua Nuevo', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13810', 'name' => 'Tiquisio', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13836', 'name' => 'Turbaco', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13838', 'name' => 'Turbaná', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13873', 'name' => 'Villanueva', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '13894', 'name' => 'Zambrano', 'department_code' => '13', 'department_name' => 'Bolívar'],
            ['code' => '15001', 'name' => 'Tunja', 'department_code' => '15', 'department_name' => 'Boyacá'],
            ['code' => '17001', 'name' => 'Manizales', 'department_code' => '17', 'department_name' => 'Caldas'],
            ['code' => '18001', 'name' => 'Florencia', 'department_code' => '18', 'department_name' => 'Caquetá'],
            ['code' => '19001', 'name' => 'Popayán', 'department_code' => '19', 'department_name' => 'Cauca'],
            ['code' => '20001', 'name' => 'Valledupar', 'department_code' => '20', 'department_name' => 'Cesar'],
            ['code' => '23001', 'name' => 'Montería', 'department_code' => '23', 'department_name' => 'Córdoba'],
            ['code' => '25001', 'name' => 'Agua de Dios', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25019', 'name' => 'Albán', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25035', 'name' => 'Anapoima', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25040', 'name' => 'Anolaima', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25053', 'name' => 'Arbeláez', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25086', 'name' => 'Beltrán', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25095', 'name' => 'Bituima', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25099', 'name' => 'Bojacá', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25120', 'name' => 'Cabrera', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25123', 'name' => 'Cachipay', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25126', 'name' => 'Cajicá', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25148', 'name' => 'Caparrapí', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25151', 'name' => 'Cáqueza', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25154', 'name' => 'Carmen de Carupa', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25168', 'name' => 'Chaguaní', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25175', 'name' => 'Chía', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25178', 'name' => 'Chipaque', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25181', 'name' => 'Choachí', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25183', 'name' => 'Chocontá', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25200', 'name' => 'Cogua', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25214', 'name' => 'Cota', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25224', 'name' => 'Cucunubá', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25245', 'name' => 'El Colegio', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25258', 'name' => 'El Peñón', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25260', 'name' => 'El Rosal', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25269', 'name' => 'Facatativá', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25279', 'name' => 'Fomeque', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25281', 'name' => 'Fosca', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25286', 'name' => 'Funza', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25288', 'name' => 'Fúquene', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25290', 'name' => 'Fusagasugá', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25293', 'name' => 'Gachalá', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25295', 'name' => 'Gachancipá', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25297', 'name' => 'Gachetá', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25299', 'name' => 'Gama', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25307', 'name' => 'Girardot', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25312', 'name' => 'Granada', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25317', 'name' => 'Guachetá', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25320', 'name' => 'Guaduas', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25322', 'name' => 'Guasca', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25324', 'name' => 'Guataquí', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25326', 'name' => 'Guatavita', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25328', 'name' => 'Guayabal de Síquima', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25335', 'name' => 'Guayabetal', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25339', 'name' => 'Gutiérrez', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25368', 'name' => 'Jerusalén', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25372', 'name' => 'Junín', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25377', 'name' => 'La Calera', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25386', 'name' => 'La Mesa', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25394', 'name' => 'La Palma', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25398', 'name' => 'La Peña', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25402', 'name' => 'La Vega', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25407', 'name' => 'Lenguazaque', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25426', 'name' => 'Macheta', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25430', 'name' => 'Madrid', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25436', 'name' => 'Manta', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25438', 'name' => 'Medina', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25473', 'name' => 'Mosquera', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25483', 'name' => 'Nariño', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25486', 'name' => 'Nemocón', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25488', 'name' => 'Nilo', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25489', 'name' => 'Nimaima', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25491', 'name' => 'Nocaima', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25506', 'name' => 'Venecia', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25513', 'name' => 'Pacho', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25518', 'name' => 'Paime', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25524', 'name' => 'Pandi', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25530', 'name' => 'Paratebueno', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25535', 'name' => 'Pasca', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25572', 'name' => 'Puerto Salgar', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25580', 'name' => 'Pulí', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25592', 'name' => 'Quebradanegra', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25594', 'name' => 'Quetame', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25596', 'name' => 'Quipile', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25599', 'name' => 'Apulo', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25612', 'name' => 'Ricaurte', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25645', 'name' => 'San Antonio del Tequendama', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25649', 'name' => 'San Bernardo', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25653', 'name' => 'San Cayetano', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25658', 'name' => 'San Francisco', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25662', 'name' => 'San Juan de Río Seco', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25718', 'name' => 'Sasaima', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25736', 'name' => 'Sesquilé', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25740', 'name' => 'Sibaté', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25743', 'name' => 'Silvania', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25745', 'name' => 'Simijaca', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25754', 'name' => 'Soacha', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25758', 'name' => 'Sopó', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25769', 'name' => 'Subachoque', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25772', 'name' => 'Suesca', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25777', 'name' => 'Supatá', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25779', 'name' => 'Susa', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25781', 'name' => 'Sutatausa', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25785', 'name' => 'Tabio', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25793', 'name' => 'Tausa', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25797', 'name' => 'Tena', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25799', 'name' => 'Tenjo', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25805', 'name' => 'Tibacuy', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25807', 'name' => 'Tibirita', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25815', 'name' => 'Tocaima', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25817', 'name' => 'Tocancipá', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25823', 'name' => 'Topaipí', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25839', 'name' => 'Ubalá', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25841', 'name' => 'Ubaque', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25843', 'name' => 'Villa de San Diego de Ubaté', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25845', 'name' => 'Une', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25851', 'name' => 'Útica', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25862', 'name' => 'Vergara', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25867', 'name' => 'Vianí', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25871', 'name' => 'Villagómez', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25873', 'name' => 'Villapinzón', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25875', 'name' => 'Villeta', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25878', 'name' => 'Viotá', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25885', 'name' => 'Yacopí', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25898', 'name' => 'Zipacón', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '25899', 'name' => 'Zipaquirá', 'department_code' => '25', 'department_name' => 'Cundinamarca'],
            ['code' => '27001', 'name' => 'Quibdó', 'department_code' => '27', 'department_name' => 'Chocó'],
            ['code' => '41001', 'name' => 'Neiva', 'department_code' => '41', 'department_name' => 'Huila'],
            ['code' => '44001', 'name' => 'Riohacha', 'department_code' => '44', 'department_name' => 'La Guajira'],
            ['code' => '47001', 'name' => 'Santa Marta', 'department_code' => '47', 'department_name' => 'Magdalena'],
            ['code' => '50001', 'name' => 'Villavicencio', 'department_code' => '50', 'department_name' => 'Meta'],
            ['code' => '52001', 'name' => 'Pasto', 'department_code' => '52', 'department_name' => 'Nariño'],
            ['code' => '54001', 'name' => 'Cúcuta', 'department_code' => '54', 'department_name' => 'Norte de Santander'],
            ['code' => '63001', 'name' => 'Armenia', 'department_code' => '63', 'department_name' => 'Quindío'],
            ['code' => '66001', 'name' => 'Pereira', 'department_code' => '66', 'department_name' => 'Risaralda'],
            ['code' => '68001', 'name' => 'Bucaramanga', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68081', 'name' => 'Barichara', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68092', 'name' => 'Betulia', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68101', 'name' => 'Bolívar', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68121', 'name' => 'Cabrera', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68132', 'name' => 'California', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68147', 'name' => 'Capitanejo', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68152', 'name' => 'Carcasí', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68160', 'name' => 'Cepitá', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68162', 'name' => 'Cerrito', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68167', 'name' => 'Charalá', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68169', 'name' => 'Charta', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68176', 'name' => 'Chima', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68179', 'name' => 'Chipatá', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68190', 'name' => 'Cimitarra', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68207', 'name' => 'Concepción', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68209', 'name' => 'Confines', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68211', 'name' => 'Contratación', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68217', 'name' => 'Coromoro', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68229', 'name' => 'Curití', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68235', 'name' => 'El Carmen de Chucurí', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68245', 'name' => 'El Guacamayo', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68250', 'name' => 'El Peñón', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68255', 'name' => 'El Playón', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68264', 'name' => 'Encino', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68266', 'name' => 'Enciso', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68271', 'name' => 'Florián', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68276', 'name' => 'Floridablanca', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68296', 'name' => 'Galán', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68298', 'name' => 'Gámbita', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68307', 'name' => 'Girón', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68318', 'name' => 'Guaca', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68320', 'name' => 'Guadalupe', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68322', 'name' => 'Guapotá', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68324', 'name' => 'Guavatá', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68327', 'name' => 'Güepsa', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68344', 'name' => 'Hato', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68368', 'name' => 'Jesús María', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68370', 'name' => 'Jordán', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68377', 'name' => 'La Belleza', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68385', 'name' => 'Landázuri', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68397', 'name' => 'La Paz', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68406', 'name' => 'Lebrija', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68418', 'name' => 'Los Santos', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68425', 'name' => 'Macaravita', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68432', 'name' => 'Málaga', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68444', 'name' => 'Matanza', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68464', 'name' => 'Mogotes', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68468', 'name' => 'Molagavita', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68498', 'name' => 'Ocamonte', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68500', 'name' => 'Oiba', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68502', 'name' => 'Onzaga', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68522', 'name' => 'Palmar', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68524', 'name' => 'Palmas del Socorro', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68533', 'name' => 'Páramo', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68547', 'name' => 'Piedecuesta', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68549', 'name' => 'Pinchote', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68572', 'name' => 'Puente Nacional', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68573', 'name' => 'Puerto Parra', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68575', 'name' => 'Puerto Wilches', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68615', 'name' => 'Rionegro', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68655', 'name' => 'Sabana de Torres', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68669', 'name' => 'San Andrés', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68673', 'name' => 'San Benito', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68679', 'name' => 'San Gil', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68682', 'name' => 'San Joaquín', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68684', 'name' => 'San José de Miranda', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68686', 'name' => 'San Miguel', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68689', 'name' => 'San Vicente de Chucurí', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68705', 'name' => 'Santa Bárbara', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68720', 'name' => 'Santa Helena del Opón', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68745', 'name' => 'Simacota', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68755', 'name' => 'Socorro', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68770', 'name' => 'Suaita', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68773', 'name' => 'Sucre', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68780', 'name' => 'Suratá', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68820', 'name' => 'El Tablón', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68855', 'name' => 'Tona', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68861', 'name' => 'Valle de San José', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68867', 'name' => 'Vélez', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68872', 'name' => 'Vetas', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68895', 'name' => 'Villanueva', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '68901', 'name' => 'Zapatoca', 'department_code' => '68', 'department_name' => 'Santander'],
            ['code' => '70001', 'name' => 'Sincelejo', 'department_code' => '70', 'department_name' => 'Sucre'],
            ['code' => '73001', 'name' => 'Ibagué', 'department_code' => '73', 'department_name' => 'Tolima'],
            ['code' => '76001', 'name' => 'Cali', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76020', 'name' => 'Alcalá', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76036', 'name' => 'Andalucía', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76041', 'name' => 'Ansermanuevo', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76054', 'name' => 'Argelia', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76100', 'name' => 'Bolívar', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76109', 'name' => 'Buenaventura', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76111', 'name' => 'Buga', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76113', 'name' => 'Bugalagrande', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76122', 'name' => 'Caicedonia', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76126', 'name' => 'Calima', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76130', 'name' => 'Candelaria', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76147', 'name' => 'Cartago', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76233', 'name' => 'Dagua', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76243', 'name' => 'El Águila', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76246', 'name' => 'El Cairo', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76248', 'name' => 'El Cerrito', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76250', 'name' => 'El Dovio', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76275', 'name' => 'Florida', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76306', 'name' => 'Ginebra', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76318', 'name' => 'Guacarí', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76364', 'name' => 'Jamundí', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76377', 'name' => 'La Cumbre', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76400', 'name' => 'La Unión', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76403', 'name' => 'La Victoria', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76497', 'name' => 'Obando', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76520', 'name' => 'Palmira', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76563', 'name' => 'Pradera', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76606', 'name' => 'Restrepo', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76616', 'name' => 'Riofrío', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76622', 'name' => 'Roldanillo', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76670', 'name' => 'San Pedro', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76736', 'name' => 'Sevilla', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76823', 'name' => 'Toro', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76828', 'name' => 'Trujillo', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76834', 'name' => 'Tuluá', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76845', 'name' => 'Ulloa', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76863', 'name' => 'Versalles', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76869', 'name' => 'Vijes', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76890', 'name' => 'Yotoco', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76892', 'name' => 'Yumbo', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '76895', 'name' => 'Zarzal', 'department_code' => '76', 'department_name' => 'Valle del Cauca'],
            ['code' => '81001', 'name' => 'Arauca', 'department_code' => '81', 'department_name' => 'Arauca'],
            ['code' => '85001', 'name' => 'Yopal', 'department_code' => '85', 'department_name' => 'Casanare'],
            ['code' => '86001', 'name' => 'Mocoa', 'department_code' => '86', 'department_name' => 'Putumayo'],
            ['code' => '88001', 'name' => 'San Andrés', 'department_code' => '88', 'department_name' => 'San Andrés y Providencia'],
            ['code' => '91001', 'name' => 'Leticia', 'department_code' => '91', 'department_name' => 'Amazonas'],
            ['code' => '94001', 'name' => 'Inírida', 'department_code' => '94', 'department_name' => 'Guainía'],
            ['code' => '95001', 'name' => 'San José del Guaviare', 'department_code' => '95', 'department_name' => 'Guaviare'],
            ['code' => '97001', 'name' => 'Mitú', 'department_code' => '97', 'department_name' => 'Vaupés'],
            ['code' => '99001', 'name' => 'Puerto Carreño', 'department_code' => '99', 'department_name' => 'Vichada'],
        ];
    }
}
